#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
合并 LeetCode 热题 100 + 面试经典 150 的清单骨架，
输出 data/index.json（id, title, titleEn, difficulty, tags）。
"""
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "index.json"

# 热题 100（中文标题、难度、标签已确定）
HOT100 = [
    {"id": 1, "title": "两数之和", "titleEn": "Two Sum", "difficulty": "简单", "tags": ["数组", "哈希表"]},
    {"id": 49, "title": "字母异位词分组", "titleEn": "Group Anagrams", "difficulty": "中等", "tags": ["数组", "哈希表", "字符串"]},
    {"id": 128, "title": "最长连续序列", "titleEn": "Longest Consecutive Sequence", "difficulty": "中等", "tags": ["并查集", "数组", "哈希表"]},
    {"id": 283, "title": "移动零", "titleEn": "Move Zeroes", "difficulty": "简单", "tags": ["数组", "双指针"]},
    {"id": 11, "title": "盛最多水的容器", "titleEn": "Container With Most Water", "difficulty": "中等", "tags": ["数组", "双指针", "贪心"]},
    {"id": 15, "title": "三数之和", "titleEn": "3Sum", "difficulty": "中等", "tags": ["数组", "双指针", "排序"]},
    {"id": 42, "title": "接雨水", "titleEn": "Trapping Rain Water", "difficulty": "困难", "tags": ["栈", "数组", "双指针", "动态规划"]},
    {"id": 3, "title": "无重复字符的最长子串", "titleEn": "Longest Substring Without Repeating Characters", "difficulty": "中等", "tags": ["哈希表", "字符串", "滑动窗口"]},
    {"id": 438, "title": "找到字符串中所有字母异位词", "titleEn": "Find All Anagrams in a String", "difficulty": "中等", "tags": ["哈希表", "字符串", "滑动窗口"]},
    {"id": 560, "title": "和为 K 的子数组", "titleEn": "Subarray Sum Equals K", "difficulty": "中等", "tags": ["数组", "哈希表", "前缀和"]},
    {"id": 239, "title": "滑动窗口最大值", "titleEn": "Sliding Window Maximum", "difficulty": "困难", "tags": ["队列", "数组", "滑动窗口", "堆"]},
    {"id": 76, "title": "最小覆盖子串", "titleEn": "Minimum Window Substring", "difficulty": "困难", "tags": ["哈希表", "字符串", "滑动窗口"]},
    {"id": 53, "title": "最大子数组和", "titleEn": "Maximum Subarray", "difficulty": "中等", "tags": ["数组", "动态规划", "分治"]},
    {"id": 56, "title": "合并区间", "titleEn": "Merge Intervals", "difficulty": "中等", "tags": ["数组", "排序"]},
    {"id": 189, "title": "轮转数组", "titleEn": "Rotate Array", "difficulty": "中等", "tags": ["数组", "数学", "双指针"]},
    {"id": 238, "title": "除自身以外数组的乘积", "titleEn": "Product of Array Except Self", "difficulty": "中等", "tags": ["数组", "前缀和"]},
    {"id": 41, "title": "缺失的第一个正数", "titleEn": "First Missing Positive", "difficulty": "困难", "tags": ["数组", "哈希表"]},
    {"id": 73, "title": "矩阵置零", "titleEn": "Set Matrix Zeroes", "difficulty": "中等", "tags": ["数组", "哈希表", "矩阵"]},
    {"id": 54, "title": "螺旋矩阵", "titleEn": "Spiral Matrix", "difficulty": "中等", "tags": ["数组", "矩阵", "模拟"]},
    {"id": 48, "title": "旋转图像", "titleEn": "Rotate Image", "difficulty": "中等", "tags": ["数组", "数学", "矩阵"]},
    {"id": 240, "title": "搜索二维矩阵 II", "titleEn": "Search a 2D Matrix II", "difficulty": "中等", "tags": ["数组", "二分查找", "分治"]},
    {"id": 160, "title": "相交链表", "titleEn": "Intersection of Two Linked Lists", "difficulty": "简单", "tags": ["哈希表", "链表", "双指针"]},
    {"id": 206, "title": "反转链表", "titleEn": "Reverse Linked List", "difficulty": "简单", "tags": ["链表", "递归"]},
    {"id": 234, "title": "回文链表", "titleEn": "Palindrome Linked List", "difficulty": "简单", "tags": ["栈", "递归", "链表"]},
    {"id": 141, "title": "环形链表", "titleEn": "Linked List Cycle", "difficulty": "简单", "tags": ["哈希表", "链表", "双指针"]},
    {"id": 142, "title": "环形链表 II", "titleEn": "Linked List Cycle II", "difficulty": "中等", "tags": ["哈希表", "链表", "双指针"]},
    {"id": 21, "title": "合并两个有序链表", "titleEn": "Merge Two Sorted Lists", "difficulty": "简单", "tags": ["递归", "链表"]},
    {"id": 2, "title": "两数相加", "titleEn": "Add Two Numbers", "difficulty": "中等", "tags": ["递归", "链表", "数学"]},
    {"id": 19, "title": "删除链表的倒数第 N 个结点", "titleEn": "Remove Nth Node From End of List", "difficulty": "中等", "tags": ["链表", "双指针"]},
    {"id": 24, "title": "两两交换链表中的节点", "titleEn": "Swap Nodes in Pairs", "difficulty": "中等", "tags": ["递归", "链表"]},
    {"id": 25, "title": "K 个一组翻转链表", "titleEn": "Reverse Nodes in k-Group", "difficulty": "困难", "tags": ["递归", "链表"]},
    {"id": 138, "title": "随机链表的复制", "titleEn": "Copy List with Random Pointer", "difficulty": "中等", "tags": ["哈希表", "链表"]},
    {"id": 148, "title": "排序链表", "titleEn": "Sort List", "difficulty": "中等", "tags": ["链表", "双指针", "分治", "排序"]},
    {"id": 23, "title": "合并 K 个升序链表", "titleEn": "Merge k Sorted Lists", "difficulty": "困难", "tags": ["链表", "分治", "堆"]},
    {"id": 146, "title": "LRU 缓存", "titleEn": "LRU Cache", "difficulty": "中等", "tags": ["设计", "哈希表", "链表"]},
    {"id": 94, "title": "二叉树的中序遍历", "titleEn": "Binary Tree Inorder Traversal", "difficulty": "简单", "tags": ["栈", "树", "深度优先搜索"]},
    {"id": 104, "title": "二叉树的最大深度", "titleEn": "Maximum Depth of Binary Tree", "difficulty": "简单", "tags": ["树", "深度优先搜索", "广度优先搜索"]},
    {"id": 226, "title": "翻转二叉树", "titleEn": "Invert Binary Tree", "difficulty": "简单", "tags": ["树", "深度优先搜索", "广度优先搜索"]},
    {"id": 101, "title": "对称二叉树", "titleEn": "Symmetric Tree", "difficulty": "简单", "tags": ["树", "深度优先搜索", "广度优先搜索"]},
    {"id": 543, "title": "二叉树的直径", "titleEn": "Diameter of Binary Tree", "difficulty": "简单", "tags": ["树", "深度优先搜索", "二叉树"]},
    {"id": 102, "title": "二叉树的层序遍历", "titleEn": "Binary Tree Level Order Traversal", "difficulty": "中等", "tags": ["树", "广度优先搜索", "二叉树"]},
    {"id": 108, "title": "将有序数组转换为二叉搜索树", "titleEn": "Convert Sorted Array to Binary Search Tree", "difficulty": "简单", "tags": ["树", "二叉搜索树", "数组", "分治"]},
    {"id": 98, "title": "验证二叉搜索树", "titleEn": "Validate Binary Search Tree", "difficulty": "中等", "tags": ["树", "深度优先搜索", "二叉搜索树"]},
    {"id": 230, "title": "二叉搜索树中第 K 小的元素", "titleEn": "Kth Smallest Element in a BST", "difficulty": "中等", "tags": ["树", "深度优先搜索", "二叉搜索树"]},
    {"id": 199, "title": "二叉树的右视图", "titleEn": "Binary Tree Right Side View", "difficulty": "中等", "tags": ["树", "深度优先搜索", "广度优先搜索"]},
    {"id": 114, "title": "二叉树展开为链表", "titleEn": "Flatten Binary Tree to Linked List", "difficulty": "中等", "tags": ["栈", "树", "深度优先搜索", "链表"]},
    {"id": 105, "title": "从前序与中序遍历序列构造二叉树", "titleEn": "Construct Binary Tree from Preorder and Inorder Traversal", "difficulty": "中等", "tags": ["树", "数组", "哈希表", "分治"]},
    {"id": 437, "title": "路径总和 III", "titleEn": "Path Sum III", "difficulty": "中等", "tags": ["树", "深度优先搜索", "二叉树"]},
    {"id": 236, "title": "二叉树的最近公共祖先", "titleEn": "Lowest Common Ancestor of a Binary Tree", "difficulty": "中等", "tags": ["树", "深度优先搜索", "二叉树"]},
    {"id": 124, "title": "二叉树中的最大路径和", "titleEn": "Binary Tree Maximum Path Sum", "difficulty": "困难", "tags": ["树", "深度优先搜索", "动态规划"]},
    {"id": 200, "title": "岛屿数量", "titleEn": "Number of Islands", "difficulty": "中等", "tags": ["深度优先搜索", "广度优先搜索", "并查集"]},
    {"id": 994, "title": "腐烂的橘子", "titleEn": "Rotting Oranges", "difficulty": "中等", "tags": ["广度优先搜索", "数组", "矩阵"]},
    {"id": 207, "title": "课程表", "titleEn": "Course Schedule", "difficulty": "中等", "tags": ["深度优先搜索", "广度优先搜索", "图"]},
    {"id": 208, "title": "实现 Trie（前缀树）", "titleEn": "Implement Trie (Prefix Tree)", "difficulty": "中等", "tags": ["设计", "字典树", "哈希表"]},
    {"id": 46, "title": "全排列", "titleEn": "Permutations", "difficulty": "中等", "tags": ["数组", "回溯"]},
    {"id": 78, "title": "子集", "titleEn": "Subsets", "difficulty": "中等", "tags": ["位运算", "数组", "回溯"]},
    {"id": 17, "title": "电话号码的字母组合", "titleEn": "Letter Combinations of a Phone Number", "difficulty": "中等", "tags": ["哈希表", "字符串", "回溯"]},
    {"id": 39, "title": "组合总和", "titleEn": "Combination Sum", "difficulty": "中等", "tags": ["数组", "回溯"]},
    {"id": 22, "title": "括号生成", "titleEn": "Generate Parentheses", "difficulty": "中等", "tags": ["字符串", "动态规划", "回溯"]},
    {"id": 79, "title": "单词搜索", "titleEn": "Word Search", "difficulty": "中等", "tags": ["深度优先搜索", "数组", "字符串", "回溯"]},
    {"id": 131, "title": "分割回文串", "titleEn": "Palindrome Partitioning", "difficulty": "中等", "tags": ["字符串", "动态规划", "回溯"]},
    {"id": 51, "title": "N 皇后", "titleEn": "N-Queens", "difficulty": "困难", "tags": ["数组", "回溯"]},
    {"id": 35, "title": "搜索插入位置", "titleEn": "Search Insert Position", "difficulty": "简单", "tags": ["数组", "二分查找"]},
    {"id": 74, "title": "搜索二维矩阵", "titleEn": "Search a 2D Matrix", "difficulty": "中等", "tags": ["数组", "二分查找", "矩阵"]},
    {"id": 34, "title": "在排序数组中查找元素的第一个和最后一个位置", "titleEn": "Find First and Last Position of Element in Sorted Array", "difficulty": "中等", "tags": ["数组", "二分查找"]},
    {"id": 33, "title": "搜索旋转排序数组", "titleEn": "Search in Rotated Sorted Array", "difficulty": "中等", "tags": ["数组", "二分查找"]},
    {"id": 153, "title": "寻找旋转排序数组中的最小值", "titleEn": "Find Minimum in Rotated Sorted Array", "difficulty": "中等", "tags": ["数组", "二分查找"]},
    {"id": 4, "title": "寻找两个正序数组的中位数", "titleEn": "Median of Two Sorted Arrays", "difficulty": "困难", "tags": ["数组", "二分查找", "分治"]},
    {"id": 20, "title": "有效的括号", "titleEn": "Valid Parentheses", "difficulty": "简单", "tags": ["栈", "字符串"]},
    {"id": 155, "title": "最小栈", "titleEn": "Min Stack", "difficulty": "中等", "tags": ["栈", "设计"]},
    {"id": 394, "title": "字符串解码", "titleEn": "Decode String", "difficulty": "中等", "tags": ["栈", "递归", "字符串"]},
    {"id": 739, "title": "每日温度", "titleEn": "Daily Temperatures", "difficulty": "中等", "tags": ["栈", "数组", "单调栈"]},
    {"id": 84, "title": "柱状图中最大的矩形", "titleEn": "Largest Rectangle in Histogram", "difficulty": "困难", "tags": ["栈", "数组", "单调栈"]},
    {"id": 215, "title": "数组中的第 K 个最大元素", "titleEn": "Kth Largest Element in an Array", "difficulty": "中等", "tags": ["数组", "分治", "快速选择", "堆"]},
    {"id": 347, "title": "前 K 个高频元素", "titleEn": "Top K Frequent Elements", "difficulty": "中等", "tags": ["数组", "哈希表", "分治", "堆"]},
    {"id": 295, "title": "数据流的中位数", "titleEn": "Find Median from Data Stream", "difficulty": "困难", "tags": ["设计", "双指针", "数据流", "堆"]},
    {"id": 121, "title": "买卖股票的最佳时机", "titleEn": "Best Time to Buy and Sell Stock", "difficulty": "简单", "tags": ["数组", "动态规划"]},
    {"id": 55, "title": "跳跃游戏", "titleEn": "Jump Game", "difficulty": "中等", "tags": ["贪心", "数组", "动态规划"]},
    {"id": 45, "title": "跳跃游戏 II", "titleEn": "Jump Game II", "difficulty": "中等", "tags": ["贪心", "数组", "动态规划"]},
    {"id": 763, "title": "划分字母区间", "titleEn": "Partition Labels", "difficulty": "中等", "tags": ["贪心", "哈希表", "双指针"]},
    {"id": 70, "title": "爬楼梯", "titleEn": "Climbing Stairs", "difficulty": "简单", "tags": ["动态规划", "记忆化搜索", "数学"]},
    {"id": 118, "title": "杨辉三角", "titleEn": "Pascal's Triangle", "difficulty": "简单", "tags": ["数组", "动态规划"]},
    {"id": 198, "title": "打家劫舍", "titleEn": "House Robber", "difficulty": "中等", "tags": ["数组", "动态规划"]},
    {"id": 279, "title": "完全平方数", "titleEn": "Perfect Squares", "difficulty": "中等", "tags": ["广度优先搜索", "数学", "动态规划"]},
    {"id": 322, "title": "零钱兑换", "titleEn": "Coin Change", "difficulty": "中等", "tags": ["动态规划", "广度优先搜索"]},
    {"id": 139, "title": "单词拆分", "titleEn": "Word Break", "difficulty": "中等", "tags": ["字典树", "记忆化搜索", "数组", "动态规划"]},
    {"id": 300, "title": "最长递增子序列", "titleEn": "Longest Increasing Subsequence", "difficulty": "中等", "tags": ["数组", "二分查找", "动态规划"]},
    {"id": 152, "title": "乘积最大子数组", "titleEn": "Maximum Product Subarray", "difficulty": "中等", "tags": ["数组", "动态规划"]},
    {"id": 416, "title": "分割等和子集", "titleEn": "Partition Equal Subset Sum", "difficulty": "中等", "tags": ["数组", "动态规划"]},
    {"id": 32, "title": "最长有效括号", "titleEn": "Longest Valid Parentheses", "difficulty": "困难", "tags": ["栈", "字符串", "动态规划"]},
    {"id": 62, "title": "不同路径", "titleEn": "Unique Paths", "difficulty": "中等", "tags": ["数学", "动态规划", "组合数学"]},
    {"id": 64, "title": "最小路径和", "titleEn": "Minimum Path Sum", "difficulty": "中等", "tags": ["数组", "动态规划", "矩阵"]},
    {"id": 5, "title": "最长回文子串", "titleEn": "Longest Palindromic Substring", "difficulty": "中等", "tags": ["双指针", "字符串", "动态规划"]},
    {"id": 1143, "title": "最长公共子序列", "titleEn": "Longest Common Subsequence", "difficulty": "中等", "tags": ["字符串", "动态规划"]},
    {"id": 72, "title": "编辑距离", "titleEn": "Edit Distance", "difficulty": "困难", "tags": ["字符串", "动态规划"]},
    {"id": 136, "title": "只出现一次的数字", "titleEn": "Single Number", "difficulty": "简单", "tags": ["位运算", "数组"]},
    {"id": 169, "title": "多数元素", "titleEn": "Majority Element", "difficulty": "简单", "tags": ["数组", "哈希表", "分治"]},
    {"id": 75, "title": "颜色分类", "titleEn": "Sort Colors", "difficulty": "中等", "tags": ["数组", "双指针", "排序"]},
    {"id": 31, "title": "下一个排列", "titleEn": "Next Permutation", "difficulty": "中等", "tags": ["数组", "双指针"]},
    {"id": 287, "title": "寻找重复数", "titleEn": "Find the Duplicate Number", "difficulty": "中等", "tags": ["位运算", "数组", "双指针"]},
]

# 面试经典 150（英文数据，需要映射为中文）
TOP150 = [
    {"id": 88, "titleEn": "Merge Sorted Array", "difficulty": "Easy", "tags": ["Array", "Two Pointers", "Sorting"]},
    {"id": 27, "titleEn": "Remove Element", "difficulty": "Easy", "tags": ["Array", "Two Pointers"]},
    {"id": 26, "titleEn": "Remove Duplicates from Sorted Array", "difficulty": "Easy", "tags": ["Array", "Two Pointers"]},
    {"id": 80, "titleEn": "Remove Duplicates from Sorted Array II", "difficulty": "Medium", "tags": ["Array", "Two Pointers"]},
    {"id": 169, "titleEn": "Majority Element", "difficulty": "Easy", "tags": ["Array", "Hash Table", "Divide and Conquer", "Sorting", "Counting"]},
    {"id": 189, "titleEn": "Rotate Array", "difficulty": "Medium", "tags": ["Array", "Math", "Two Pointers"]},
    {"id": 122, "titleEn": "Best Time to Buy and Sell Stock II", "difficulty": "Medium", "tags": ["Array", "Dynamic Programming", "Greedy"]},
    {"id": 274, "titleEn": "H-Index", "difficulty": "Medium", "tags": ["Array", "Sorting", "Counting Sort"]},
    {"id": 380, "titleEn": "Insert Delete GetRandom O(1)", "difficulty": "Medium", "tags": ["Array", "Hash Table", "Math", "Design", "Randomized"]},
    {"id": 134, "titleEn": "Gas Station", "difficulty": "Medium", "tags": ["Array", "Greedy"]},
    {"id": 135, "titleEn": "Candy", "difficulty": "Hard", "tags": ["Array", "Greedy"]},
    {"id": 13, "titleEn": "Roman to Integer", "difficulty": "Easy", "tags": ["Hash Table", "Math", "String"]},
    {"id": 12, "titleEn": "Integer to Roman", "difficulty": "Medium", "tags": ["Hash Table", "Math", "String"]},
    {"id": 58, "titleEn": "Length of Last Word", "difficulty": "Easy", "tags": ["String"]},
    {"id": 14, "titleEn": "Longest Common Prefix", "difficulty": "Easy", "tags": ["String", "Trie"]},
    {"id": 151, "titleEn": "Reverse Words in a String", "difficulty": "Medium", "tags": ["Two Pointers", "String"]},
    {"id": 6, "titleEn": "Zigzag Conversion", "difficulty": "Medium", "tags": ["String"]},
    {"id": 28, "titleEn": "Find the Index of the First Occurrence in a String", "difficulty": "Easy", "tags": ["Two Pointers", "String", "String Matching"]},
    {"id": 68, "titleEn": "Text Justification", "difficulty": "Hard", "tags": ["Array", "String", "Simulation"]},
    {"id": 125, "titleEn": "Valid Palindrome", "difficulty": "Easy", "tags": ["Two Pointers", "String"]},
    {"id": 392, "titleEn": "Is Subsequence", "difficulty": "Easy", "tags": ["Two Pointers", "String", "Dynamic Programming"]},
    {"id": 167, "titleEn": "Two Sum II - Input Array Is Sorted", "difficulty": "Medium", "tags": ["Array", "Two Pointers", "Binary Search"]},
    {"id": 209, "titleEn": "Minimum Size Subarray Sum", "difficulty": "Medium", "tags": ["Array", "Binary Search", "Sliding Window", "Prefix Sum"]},
    {"id": 30, "titleEn": "Substring with Concatenation of All Words", "difficulty": "Hard", "tags": ["Hash Table", "String", "Sliding Window"]},
    {"id": 36, "titleEn": "Valid Sudoku", "difficulty": "Medium", "tags": ["Array", "Hash Table", "Matrix"]},
    {"id": 289, "titleEn": "Game of Life", "difficulty": "Medium", "tags": ["Array", "Matrix", "Simulation"]},
    {"id": 383, "titleEn": "Ransom Note", "difficulty": "Easy", "tags": ["Hash Table", "String", "Counting"]},
    {"id": 205, "titleEn": "Isomorphic Strings", "difficulty": "Easy", "tags": ["Hash Table", "String"]},
    {"id": 290, "titleEn": "Word Pattern", "difficulty": "Easy", "tags": ["Hash Table", "String"]},
    {"id": 242, "titleEn": "Valid Anagram", "difficulty": "Easy", "tags": ["Hash Table", "String", "Sorting"]},
    {"id": 202, "titleEn": "Happy Number", "difficulty": "Easy", "tags": ["Hash Table", "Math", "Two Pointers"]},
    {"id": 219, "titleEn": "Contains Duplicate II", "difficulty": "Easy", "tags": ["Array", "Hash Table", "Sliding Window"]},
    {"id": 228, "titleEn": "Summary Ranges", "difficulty": "Easy", "tags": ["Array"]},
    {"id": 57, "titleEn": "Insert Interval", "difficulty": "Medium", "tags": ["Array"]},
    {"id": 452, "titleEn": "Minimum Number of Arrows to Burst Balloons", "difficulty": "Medium", "tags": ["Array", "Greedy", "Sorting"]},
    {"id": 71, "titleEn": "Simplify Path", "difficulty": "Medium", "tags": ["String", "Stack"]},
    {"id": 150, "titleEn": "Evaluate Reverse Polish Notation", "difficulty": "Medium", "tags": ["Array", "Math", "Stack"]},
    {"id": 224, "titleEn": "Basic Calculator", "difficulty": "Hard", "tags": ["Math", "String", "Stack", "Recursion"]},
    {"id": 92, "titleEn": "Reverse Linked List II", "difficulty": "Medium", "tags": ["Linked List"]},
    {"id": 82, "titleEn": "Remove Duplicates from Sorted List II", "difficulty": "Medium", "tags": ["Linked List", "Two Pointers"]},
    {"id": 61, "titleEn": "Rotate List", "difficulty": "Medium", "tags": ["Linked List", "Two Pointers"]},
    {"id": 86, "titleEn": "Partition List", "difficulty": "Medium", "tags": ["Linked List", "Two Pointers"]},
    {"id": 100, "titleEn": "Same Tree", "difficulty": "Easy", "tags": ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"]},
    {"id": 105, "titleEn": "Construct Binary Tree from Preorder and Inorder Traversal", "difficulty": "Medium", "tags": ["Array", "Hash Table", "Divide and Conquer", "Tree", "Binary Tree"]},
    {"id": 106, "titleEn": "Construct Binary Tree from Inorder and Postorder Traversal", "difficulty": "Medium", "tags": ["Array", "Hash Table", "Divide and Conquer", "Tree", "Binary Tree"]},
    {"id": 117, "titleEn": "Populating Next Right Pointers in Each Node II", "difficulty": "Medium", "tags": ["Linked List", "Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"]},
    {"id": 112, "titleEn": "Path Sum", "difficulty": "Easy", "tags": ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"]},
    {"id": 129, "titleEn": "Sum Root to Leaf Numbers", "difficulty": "Medium", "tags": ["Tree", "Depth-First Search", "Binary Tree"]},
    {"id": 173, "titleEn": "Binary Search Tree Iterator", "difficulty": "Medium", "tags": ["Stack", "Tree", "Design", "Binary Search Tree", "Binary Tree", "Iterator"]},
    {"id": 222, "titleEn": "Count Complete Tree Nodes", "difficulty": "Easy", "tags": ["Binary Search", "Bit Manipulation", "Tree", "Binary Tree"]},
    {"id": 637, "titleEn": "Average of Levels in Binary Tree", "difficulty": "Easy", "tags": ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"]},
    {"id": 103, "titleEn": "Binary Tree Zigzag Level Order Traversal", "difficulty": "Medium", "tags": ["Tree", "Breadth-First Search", "Binary Tree"]},
    {"id": 530, "titleEn": "Minimum Absolute Difference in BST", "difficulty": "Easy", "tags": ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Search Tree", "Binary Tree"]},
    {"id": 130, "titleEn": "Surrounded Regions", "difficulty": "Medium", "tags": ["Array", "Depth-First Search", "Breadth-First Search", "Union Find", "Matrix"]},
    {"id": 133, "titleEn": "Clone Graph", "difficulty": "Medium", "tags": ["Hash Table", "Depth-First Search", "Breadth-First Search", "Graph"]},
    {"id": 399, "titleEn": "Evaluate Division", "difficulty": "Medium", "tags": ["Array", "String", "Depth-First Search", "Breadth-First Search", "Union Find", "Graph", "Shortest Path"]},
    {"id": 210, "titleEn": "Course Schedule II", "difficulty": "Medium", "tags": ["Depth-First Search", "Breadth-First Search", "Graph", "Topological Sort"]},
    {"id": 909, "titleEn": "Snakes and Ladders", "difficulty": "Medium", "tags": ["Array", "Breadth-First Search", "Matrix"]},
    {"id": 433, "titleEn": "Minimum Genetic Mutation", "difficulty": "Medium", "tags": ["Hash Table", "String", "Breadth-First Search"]},
    {"id": 127, "titleEn": "Word Ladder", "difficulty": "Hard", "tags": ["Hash Table", "String", "Breadth-First Search"]},
    {"id": 211, "titleEn": "Design Add and Search Words Data Structure", "difficulty": "Medium", "tags": ["String", "Depth-First Search", "Design", "Trie"]},
    {"id": 212, "titleEn": "Word Search II", "difficulty": "Hard", "tags": ["Array", "String", "Backtracking", "Trie", "Matrix"]},
    {"id": 77, "titleEn": "Combinations", "difficulty": "Medium", "tags": ["Backtracking"]},
    {"id": 52, "titleEn": "N-Queens II", "difficulty": "Hard", "tags": ["Backtracking"]},
    {"id": 108, "titleEn": "Convert Sorted Array to Binary Search Tree", "difficulty": "Easy", "tags": ["Array", "Divide and Conquer", "Tree", "Binary Search Tree", "Binary Tree"]},
    {"id": 427, "titleEn": "Construct Quad Tree", "difficulty": "Medium", "tags": ["Array", "Divide and Conquer", "Tree", "Matrix"]},
    {"id": 918, "titleEn": "Maximum Sum Circular Subarray", "difficulty": "Medium", "tags": ["Array", "Divide and Conquer", "Dynamic Programming", "Queue", "Monotonic Queue"]},
    {"id": 162, "titleEn": "Find Peak Element", "difficulty": "Medium", "tags": ["Array", "Binary Search"]},
    {"id": 502, "titleEn": "IPO", "difficulty": "Hard", "tags": ["Array", "Greedy", "Sorting", "Heap (Priority Queue)"]},
    {"id": 373, "titleEn": "Find K Pairs with Smallest Sums", "difficulty": "Medium", "tags": ["Array", "Heap (Priority Queue)"]},
    {"id": 67, "titleEn": "Add Binary", "difficulty": "Easy", "tags": ["Math", "String", "Bit Manipulation", "Simulation"]},
    {"id": 190, "titleEn": "Reverse Bits", "difficulty": "Easy", "tags": ["Divide and Conquer", "Bit Manipulation"]},
    {"id": 191, "titleEn": "Number of 1 Bits", "difficulty": "Easy", "tags": ["Divide and Conquer", "Bit Manipulation"]},
    {"id": 137, "titleEn": "Single Number II", "difficulty": "Medium", "tags": ["Array", "Bit Manipulation"]},
    {"id": 201, "titleEn": "Bitwise AND of Numbers Range", "difficulty": "Medium", "tags": ["Bit Manipulation"]},
    {"id": 9, "titleEn": "Palindrome Number", "difficulty": "Easy", "tags": ["Math"]},
    {"id": 66, "titleEn": "Plus One", "difficulty": "Easy", "tags": ["Array", "Math"]},
    {"id": 172, "titleEn": "Factorial Trailing Zeroes", "difficulty": "Medium", "tags": ["Math"]},
    {"id": 69, "titleEn": "Sqrt(x)", "difficulty": "Easy", "tags": ["Math", "Binary Search"]},
    {"id": 50, "titleEn": "Pow(x, n)", "difficulty": "Medium", "tags": ["Math", "Recursion"]},
    {"id": 149, "titleEn": "Max Points on a Line", "difficulty": "Hard", "tags": ["Array", "Hash Table", "Math", "Geometry"]},
    {"id": 120, "titleEn": "Triangle", "difficulty": "Medium", "tags": ["Array", "Dynamic Programming"]},
    {"id": 63, "titleEn": "Unique Paths II", "difficulty": "Medium", "tags": ["Array", "Dynamic Programming", "Matrix"]},
    {"id": 97, "titleEn": "Interleaving String", "difficulty": "Medium", "tags": ["String", "Dynamic Programming"]},
    {"id": 123, "titleEn": "Best Time to Buy and Sell Stock III", "difficulty": "Hard", "tags": ["Array", "Dynamic Programming"]},
    {"id": 188, "titleEn": "Best Time to Buy and Sell Stock IV", "difficulty": "Hard", "tags": ["Array", "Dynamic Programming"]},
    {"id": 221, "titleEn": "Maximal Square", "difficulty": "Medium", "tags": ["Array", "Dynamic Programming", "Matrix"]},
]

# 英文题目标题 → 中文题目标题（面试 150 中需要翻译的常用题）
TITLE_MAP = {
    "Merge Sorted Array": "合并两个有序数组",
    "Remove Element": "移除元素",
    "Remove Duplicates from Sorted Array": "删除有序数组中的重复项",
    "Remove Duplicates from Sorted Array II": "删除有序数组中的重复项 II",
    "Best Time to Buy and Sell Stock II": "买卖股票的最佳时机 II",
    "H-Index": "H 指数",
    "Insert Delete GetRandom O(1)": "O(1) 时间插入、删除和获取随机元素",
    "Gas Station": "加油站",
    "Candy": "分发糖果",
    "Roman to Integer": "罗马数字转整数",
    "Integer to Roman": "整数转罗马数字",
    "Length of Last Word": "最后一个单词的长度",
    "Longest Common Prefix": "最长公共前缀",
    "Reverse Words in a String": "反转字符串中的单词",
    "Zigzag Conversion": "Z 字形变换",
    "Find the Index of the First Occurrence in a String": "找出字符串中第一个匹配项的下标",
    "Text Justification": "文本左右对齐",
    "Valid Palindrome": "验证回文串",
    "Is Subsequence": "判断子序列",
    "Two Sum II - Input Array Is Sorted": "两数之和 II - 输入有序数组",
    "Minimum Size Subarray Sum": "长度最小的子数组",
    "Substring with Concatenation of All Words": "串联所有单词的子串",
    "Valid Sudoku": "有效的数独",
    "Game of Life": "生命游戏",
    "Ransom Note": "赎金信",
    "Isomorphic Strings": "同构字符串",
    "Word Pattern": "单词规律",
    "Valid Anagram": "有效的字母异位词",
    "Happy Number": "快乐数",
    "Contains Duplicate II": "存在重复元素 II",
    "Summary Ranges": "汇总区间",
    "Insert Interval": "插入区间",
    "Minimum Number of Arrows to Burst Balloons": "用最少数量的箭引爆气球",
    "Simplify Path": "简化路径",
    "Evaluate Reverse Polish Notation": "逆波兰表达式求值",
    "Basic Calculator": "基本计算器",
    "Reverse Linked List II": "反转链表 II",
    "Remove Duplicates from Sorted List II": "删除排序链表中的重复元素 II",
    "Rotate List": "旋转链表",
    "Partition List": "分隔链表",
    "Same Tree": "相同的树",
    "Construct Binary Tree from Preorder and Inorder Traversal": "从前序与中序遍历序列构造二叉树",
    "Construct Binary Tree from Inorder and Postorder Traversal": "从中序与后序遍历序列构造二叉树",
    "Populating Next Right Pointers in Each Node II": "填充每个节点的下一个右侧节点指针 II",
    "Path Sum": "路径总和",
    "Sum Root to Leaf Numbers": "求根节点到叶节点数字之和",
    "Binary Search Tree Iterator": "二叉搜索树迭代器",
    "Count Complete Tree Nodes": "完全二叉树的节点个数",
    "Average of Levels in Binary Tree": "二叉树的层平均值",
    "Binary Tree Zigzag Level Order Traversal": "二叉树的锯齿形层序遍历",
    "Minimum Absolute Difference in BST": "二叉搜索树的最小绝对差",
    "Surrounded Regions": "被围绕的区域",
    "Clone Graph": "克隆图",
    "Evaluate Division": "除法求值",
    "Course Schedule II": "课程表 II",
    "Snakes and Ladders": "蛇梯棋",
    "Minimum Genetic Mutation": "最小基因变化",
    "Word Ladder": "单词接龙",
    "Design Add and Search Words Data Structure": "添加与搜索单词 - 数据结构设计",
    "Word Search II": "单词搜索 II",
    "Combinations": "组合",
    "N-Queens II": "N 皇后 II",
    "Convert Sorted Array to Binary Search Tree": "将有序数组转换为二叉搜索树",
    "Construct Quad Tree": "建立四叉树",
    "Maximum Sum Circular Subarray": "环形子数组的最大和",
    "Find Peak Element": "寻找峰值",
    "IPO": "IPO",
    "Find K Pairs with Smallest Sums": "查找和最小的 K 对数字",
    "Add Binary": "二进制求和",
    "Reverse Bits": "颠倒二进制位",
    "Number of 1 Bits": "位 1 的个数",
    "Single Number II": "只出现一次的数字 II",
    "Bitwise AND of Numbers Range": "数字范围按位与",
    "Palindrome Number": "回文数",
    "Plus One": "加一",
    "Factorial Trailing Zeroes": "阶乘后的零",
    "Sqrt(x)": "x 的平方根",
    "Pow(x, n)": "Pow(x, n)",
    "Max Points on a Line": "直线上最多的点数",
    "Triangle": "三角形最小路径和",
    "Unique Paths II": "不同路径 II",
    "Interleaving String": "交错字符串",
    "Best Time to Buy and Sell Stock III": "买卖股票的最佳时机 III",
    "Best Time to Buy and Sell Stock IV": "买卖股票的最佳时机 IV",
    "Maximal Square": "最大正方形",
}

# 英文标签 → 中文标签
TAG_MAP = {
    "Array": "数组",
    "Two Pointers": "双指针",
    "Sorting": "排序",
    "Hash Table": "哈希表",
    "String": "字符串",
    "Divide and Conquer": "分治",
    "Counting": "计数",
    "Counting Sort": "计数排序",
    "Math": "数学",
    "Dynamic Programming": "动态规划",
    "Greedy": "贪心",
    "Binary Search": "二分查找",
    "Stack": "栈",
    "Design": "设计",
    "Randomized": "随机化",
    "Prefix Sum": "前缀和",
    "Sliding Window": "滑动窗口",
    "Trie": "字典树",
    "Linked List": "链表",
    "Recursion": "递归",
    "Tree": "树",
    "Depth-First Search": "深度优先搜索",
    "Breadth-First Search": "广度优先搜索",
    "Binary Tree": "二叉树",
    "Binary Search Tree": "二叉搜索树",
    "Iterator": "迭代器",
    "Bit Manipulation": "位运算",
    "Matrix": "矩阵",
    "Simulation": "模拟",
    "Graph": "图",
    "Union Find": "并查集",
    "Topological Sort": "拓扑排序",
    "Shortest Path": "最短路径",
    "Backtracking": "回溯",
    "Heap (Priority Queue)": "堆",
    "Queue": "队列",
    "Monotonic Queue": "单调队列",
    "Monotonic Stack": "单调栈",
    "Data Stream": "数据流",
    "Memoization": "记忆化搜索",
    "Geometry": "几何",
}

DIFFICULTY_MAP = {"Easy": "简单", "Medium": "中等", "Hard": "困难"}


def normalize_top150(items):
    out = []
    for it in items:
        en_title = it["titleEn"]
        zh_title = TITLE_MAP.get(en_title, en_title)
        zh_tags = []
        for t in it["tags"]:
            zh_tags.append(TAG_MAP.get(t, t))
        out.append({
            "id": it["id"],
            "title": zh_title,
            "titleEn": en_title,
            "difficulty": DIFFICULTY_MAP[it["difficulty"]],
            "tags": zh_tags,
        })
    return out


def build_index():
    merged = {it["id"]: it for it in HOT100}
    for it in normalize_top150(TOP150):
        pid = it["id"]
        if pid in merged:
            # 合并标签
            existing = merged[pid]
            tags_set = set(existing["tags"] + it["tags"])
            existing["tags"] = sorted(tags_set, key=lambda x: (x != existing["tags"][0] if existing["tags"] else False, x))
            # 保留更完整的中文标题
            if len(it["title"]) >= len(existing["title"]):
                existing["title"] = it["title"]
            if len(it["titleEn"]) >= len(existing["titleEn"]):
                existing["titleEn"] = it["titleEn"]
        else:
            merged[pid] = it
    problems = sorted(merged.values(), key=lambda x: x["id"])
    return {
        "version": 1,
        "updated": "2026-08-15",
        "source": "LeetCode 热题 100 + 面试经典 150（合并去重）",
        "count": len(problems),
        "problems": problems,
    }


if __name__ == "__main__":
    OUT.parent.mkdir(parents=True, exist_ok=True)
    data = build_index()
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Generated {OUT} with {data['count']} problems.")
